version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building app..."
      - echo "Build completed on $(date)"
artifacts:
  files:
    - '**/*'
